### ISSUE TITLE
Make spy_point_name optional for bond.spy

### ISSUE THREAD

**Issue by necula01** [necula01/bond#13]
Not all spy point use agents. If you do not have an agent, the spy point name plays only a documentation role. Sometimes I just want to spy "x". I would like to be able to write:

```
bond.spy(x = x)
```
instead of 
```
bond.spy("my point", x = x)
```

Possible implementation
* Add a separate spy_anon (for anonymous spying). This will work well in all languages, but I would rather not create another entry point just for this. 
* Make the spy_point_name an optional keyword argument. If not present, then it is anonymous. This works well in Python (at the extra cost of having to type spy_point_name='foo'). We'd have to do something else for Java.

**Comment by xkrogen** [comment]
Made it so that in ruby, the first parameter is optional (not keyworded). So you can do: 
`spy(key: val, key2: val2)` or `spy('point_name', key: val)`

I thought this was a little nicer than having to do `spy(spy_point_name: 'point_name', key: val)` and forces the point name to be at the start of the argument list which is good anyway.

**Comment by necula01** [comment]
That is indeed nicer, and it happens to work the same in python too.

George.
