### ISSUE TITLE
bond_reconcile can be invoked even on test failure

### ISSUE THREAD

**Issue by necula01** [necula01/bond#14]
Right now on test failure, we do not invoke reconcile, and we cannot see the differences. 

We will add another parameter to bond_reconcile:
   --no-save="Test failed"

In the no-save mode, you can see differences, but no merging is enabled (kdiff3 used in diff-view mode only).

**Comment by xkrogen** [comment]
Why is it set up within bond_reconcile such that the diff isn't printed if
the test failed? If you want it that way so that you just print a log of
the observations thus far instead of a diff that's fine, but right now the
message is misleading:

bond_reconcile.py:238 prints "These are the differences for {}", but
doesn't actually print any differences

**Comment by xkrogen** [comment]
Actually, I see now that you can use [d]iff to show the diff. The message
is still confusing, though.

**Comment by xkrogen** [comment]
Fixed in rbond with above commit. @necula01 what do you want to do about the message? I was thinking of just changing it to: "Observations are shown for {}. Saving them not allowed. Use the diff option to show the differences." or something along those lines.

**Comment by necula01** [comment]
I agree that the message is confusing, but when working with it I have
discovered that I actually want to see the error message first, and then,
maybe, see the diff.

George.

**Comment by necula01** [comment]
I think that your proposal is fine.

George.

**Comment by xkrogen** [comment]
Updated to use the message I proposed
