### ISSUE TITLE
How to serialize object instances

### ISSUE THREAD

**Issue by necula01** [necula01/bond#5]
In the old Bond I have a custom serializer that the json module invokes when it cannot serialize the object. Then I look for a special method toJSON, and if I find it then I serialize. What should we do in the new version?

**Comment by xkrogen** [comment]
I like objects having their own toJSON method, but it might be nice to additionally make it so you can specify a serializer in the test (though maybe formatter can take this role?). toJSON generally provides nice OOP-style encapsulation but if it's only for testing purposes then you're doing a small amount of production code pollution. 

Is toJSON standard in Python (e.g. to_json is standard in Ruby because the json stdlib uses it)? If not then I don't feel quite as good about it

**Comment by necula01** [comment]
Unfortunately there is nothing standard for this purpose in Python. And you
are right that the formatter can play this role.

George.

**Comment by xkrogen** [comment]
We can also just call str() on the object as a default? And if you want something more expressive then you can specify it in the formatter?

**Comment by necula01** [comment]
I think that it is actually reasonable to write a to_json method on objects for the purpose of testing. It is true that it is in production code but this code really belongs in that class. Let's use the name "to_json" the same one for both Ruby and Python.

**Comment by necula01** [comment]
I had to bite this bullet for the project I just converted. I am using to_json. Let's use the same for Ruby.

**Comment by xkrogen** [comment]
Not yet sure how to do this in Ruby, since the built-in JSON serializer doesn't have the same option as Python for accepting a custom serializer. I will investigate further when I have a chance.

**Comment by necula01** [comment]
I thought that you said in a past message that the serializer will use
to_json if it exists.

George.

**Comment by xkrogen** [comment]
Okay, that's true, I just got confused for a bit because to_json needs to have an argument. Things will work out of the box in Ruby; I'll update the documentation to reflect this.
